FROM ubuntu
RUN apt-get update && \
	apt-get install -y supervisor gcc && \
	apt-get clean all
COPY addrinfo.c / 
RUN gcc -o dnsresolv /addrinfo.c
RUN apt-get autoremove -y gcc && \
	apt-get clean all
COPY supervisord.conf /etc/supervisor/supervisord.conf
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/supervisord.conf"]
